### ISSUE TITLE
server crash 

### ISSUE THREAD

**Issue by jprocket45** [jredfox/evilnotchlib#10] opened 2018-09-02 14:38 UTC
Version:Snapshots  64,65,66
Issue: start server it crashes remove EvilNotch Lib is starts fine
Steps to reproduce:add EvilNotch Lib to mod pack is all i can reproduce...
CrashReport   https://pastebin.com/6YGwfTdW

**Comment by jredfox** [comment] 2018-09-02 14:54
hi thank you for reporting bugs. Bug reports help improve the mod as the bug/crash-report as it could get resolved as well as inform me and others upon this issue.

can this be reproduced with just the lib itself?

**Comment by jprocket45** [comment] 2018-09-02 15:08
it crashes with just lib installed yes i tried adding in silkspawners and it still crashes would you like another crash report?

**Comment by jprocket45** [comment] 2018-09-02 15:11
https://pastebin.com/sCakDA4e

**Comment by jprocket45** [comment] 2018-09-02 15:14
also without silkspawners    https://pastebin.com/Uzed7KpE

**Comment by jredfox** [comment] 2018-09-02 15:35
no that's fine I should have this fixed by tomorrow if not the next day. I have to make my asm stable again since I have been adding stuffs.

**Comment by jprocket45** [comment] 2018-09-02 15:42
its np i should of reported this earlier ive known for days this was a issue thanks for all the hard work!! look forward to the update!!

**Comment by jredfox** [comment] 2018-09-02 15:50
it's the fact of I didn't check what side the field was before storing it into the main one. I need to switch it to the client only one that's all. The field string is for reflection since everything is private in newer versions and I needed to access something.

**Comment by jredfox** [comment] 2018-09-03 00:15
fixed this issue but, it's going to be a day or two for the asm to become done stablized and bytecode verified before I can upload the fix to curseforge at the minimum

**Closed as completed by jredfox** 2018-09-03 00:15 UTC
Labels: bug, fixed next release
